/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as SecurityRouteImport } from './routes/security'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as PortfolioRouteImport } from './routes/portfolio'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CardRouteImport } from './routes/card'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DemoIndexRouteImport } from './routes/demo/index'
import { Route as ServicesSlugRouteImport } from './routes/services.$slug'
import { Route as DemoSalonRouteImport } from './routes/demo/salon'
import { Route as DemoRestaurantRouteImport } from './routes/demo/restaurant'
import { Route as DemoRealestateRouteImport } from './routes/demo/realestate'
import { Route as DemoPlumbingRouteImport } from './routes/demo/plumbing'
import { Route as DemoPhotographyRouteImport } from './routes/demo/photography'
import { Route as DemoLawyerRouteImport } from './routes/demo/lawyer'
import { Route as DemoLandscapingRouteImport } from './routes/demo/landscaping'
import { Route as DemoFitnessRouteImport } from './routes/demo/fitness'
import { Route as DemoDentalRouteImport } from './routes/demo/dental'
import { Route as DemoAutorepairRouteImport } from './routes/demo/autorepair'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const SecurityRoute = SecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioRoute = PortfolioRouteImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CardRoute = CardRouteImport.update({
  id: '/card',
  path: '/card',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoIndexRoute = DemoIndexRouteImport.update({
  id: '/demo/',
  path: '/demo/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesSlugRoute = ServicesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ServicesRoute,
} as any)
const DemoSalonRoute = DemoSalonRouteImport.update({
  id: '/demo/salon',
  path: '/demo/salon',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoRestaurantRoute = DemoRestaurantRouteImport.update({
  id: '/demo/restaurant',
  path: '/demo/restaurant',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoRealestateRoute = DemoRealestateRouteImport.update({
  id: '/demo/realestate',
  path: '/demo/realestate',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoPlumbingRoute = DemoPlumbingRouteImport.update({
  id: '/demo/plumbing',
  path: '/demo/plumbing',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoPhotographyRoute = DemoPhotographyRouteImport.update({
  id: '/demo/photography',
  path: '/demo/photography',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoLawyerRoute = DemoLawyerRouteImport.update({
  id: '/demo/lawyer',
  path: '/demo/lawyer',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoLandscapingRoute = DemoLandscapingRouteImport.update({
  id: '/demo/landscaping',
  path: '/demo/landscaping',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoFitnessRoute = DemoFitnessRouteImport.update({
  id: '/demo/fitness',
  path: '/demo/fitness',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoDentalRoute = DemoDentalRouteImport.update({
  id: '/demo/dental',
  path: '/demo/dental',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoAutorepairRoute = DemoAutorepairRouteImport.update({
  id: '/demo/autorepair',
  path: '/demo/autorepair',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/card': typeof CardRoute
  '/contact': typeof ContactRoute
  '/portfolio': typeof PortfolioRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/security': typeof SecurityRoute
  '/services': typeof ServicesRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/demo/autorepair': typeof DemoAutorepairRoute
  '/demo/dental': typeof DemoDentalRoute
  '/demo/fitness': typeof DemoFitnessRoute
  '/demo/landscaping': typeof DemoLandscapingRoute
  '/demo/lawyer': typeof DemoLawyerRoute
  '/demo/photography': typeof DemoPhotographyRoute
  '/demo/plumbing': typeof DemoPlumbingRoute
  '/demo/realestate': typeof DemoRealestateRoute
  '/demo/restaurant': typeof DemoRestaurantRoute
  '/demo/salon': typeof DemoSalonRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/demo/': typeof DemoIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/card': typeof CardRoute
  '/contact': typeof ContactRoute
  '/portfolio': typeof PortfolioRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/security': typeof SecurityRoute
  '/services': typeof ServicesRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/demo/autorepair': typeof DemoAutorepairRoute
  '/demo/dental': typeof DemoDentalRoute
  '/demo/fitness': typeof DemoFitnessRoute
  '/demo/landscaping': typeof DemoLandscapingRoute
  '/demo/lawyer': typeof DemoLawyerRoute
  '/demo/photography': typeof DemoPhotographyRoute
  '/demo/plumbing': typeof DemoPlumbingRoute
  '/demo/realestate': typeof DemoRealestateRoute
  '/demo/restaurant': typeof DemoRestaurantRoute
  '/demo/salon': typeof DemoSalonRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/demo': typeof DemoIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/card': typeof CardRoute
  '/contact': typeof ContactRoute
  '/portfolio': typeof PortfolioRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/security': typeof SecurityRoute
  '/services': typeof ServicesRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/demo/autorepair': typeof DemoAutorepairRoute
  '/demo/dental': typeof DemoDentalRoute
  '/demo/fitness': typeof DemoFitnessRoute
  '/demo/landscaping': typeof DemoLandscapingRoute
  '/demo/lawyer': typeof DemoLawyerRoute
  '/demo/photography': typeof DemoPhotographyRoute
  '/demo/plumbing': typeof DemoPlumbingRoute
  '/demo/realestate': typeof DemoRealestateRoute
  '/demo/restaurant': typeof DemoRestaurantRoute
  '/demo/salon': typeof DemoSalonRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/demo/': typeof DemoIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/card'
    | '/contact'
    | '/portfolio'
    | '/pricing'
    | '/privacy'
    | '/security'
    | '/services'
    | '/sitemap.xml'
    | '/terms'
    | '/demo/autorepair'
    | '/demo/dental'
    | '/demo/fitness'
    | '/demo/landscaping'
    | '/demo/lawyer'
    | '/demo/photography'
    | '/demo/plumbing'
    | '/demo/realestate'
    | '/demo/restaurant'
    | '/demo/salon'
    | '/services/$slug'
    | '/demo/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/card'
    | '/contact'
    | '/portfolio'
    | '/pricing'
    | '/privacy'
    | '/security'
    | '/services'
    | '/sitemap.xml'
    | '/terms'
    | '/demo/autorepair'
    | '/demo/dental'
    | '/demo/fitness'
    | '/demo/landscaping'
    | '/demo/lawyer'
    | '/demo/photography'
    | '/demo/plumbing'
    | '/demo/realestate'
    | '/demo/restaurant'
    | '/demo/salon'
    | '/services/$slug'
    | '/demo'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/card'
    | '/contact'
    | '/portfolio'
    | '/pricing'
    | '/privacy'
    | '/security'
    | '/services'
    | '/sitemap.xml'
    | '/terms'
    | '/demo/autorepair'
    | '/demo/dental'
    | '/demo/fitness'
    | '/demo/landscaping'
    | '/demo/lawyer'
    | '/demo/photography'
    | '/demo/plumbing'
    | '/demo/realestate'
    | '/demo/restaurant'
    | '/demo/salon'
    | '/services/$slug'
    | '/demo/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  CardRoute: typeof CardRoute
  ContactRoute: typeof ContactRoute
  PortfolioRoute: typeof PortfolioRoute
  PricingRoute: typeof PricingRoute
  PrivacyRoute: typeof PrivacyRoute
  SecurityRoute: typeof SecurityRoute
  ServicesRoute: typeof ServicesRouteWithChildren
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TermsRoute: typeof TermsRoute
  DemoAutorepairRoute: typeof DemoAutorepairRoute
  DemoDentalRoute: typeof DemoDentalRoute
  DemoFitnessRoute: typeof DemoFitnessRoute
  DemoLandscapingRoute: typeof DemoLandscapingRoute
  DemoLawyerRoute: typeof DemoLawyerRoute
  DemoPhotographyRoute: typeof DemoPhotographyRoute
  DemoPlumbingRoute: typeof DemoPlumbingRoute
  DemoRealestateRoute: typeof DemoRealestateRoute
  DemoRestaurantRoute: typeof DemoRestaurantRoute
  DemoSalonRoute: typeof DemoSalonRoute
  DemoIndexRoute: typeof DemoIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/security': {
      id: '/security'
      path: '/security'
      fullPath: '/security'
      preLoaderRoute: typeof SecurityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio': {
      id: '/portfolio'
      path: '/portfolio'
      fullPath: '/portfolio'
      preLoaderRoute: typeof PortfolioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/card': {
      id: '/card'
      path: '/card'
      fullPath: '/card'
      preLoaderRoute: typeof CardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/': {
      id: '/demo/'
      path: '/demo'
      fullPath: '/demo/'
      preLoaderRoute: typeof DemoIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/$slug': {
      id: '/services/$slug'
      path: '/$slug'
      fullPath: '/services/$slug'
      preLoaderRoute: typeof ServicesSlugRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/demo/salon': {
      id: '/demo/salon'
      path: '/demo/salon'
      fullPath: '/demo/salon'
      preLoaderRoute: typeof DemoSalonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/restaurant': {
      id: '/demo/restaurant'
      path: '/demo/restaurant'
      fullPath: '/demo/restaurant'
      preLoaderRoute: typeof DemoRestaurantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/realestate': {
      id: '/demo/realestate'
      path: '/demo/realestate'
      fullPath: '/demo/realestate'
      preLoaderRoute: typeof DemoRealestateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/plumbing': {
      id: '/demo/plumbing'
      path: '/demo/plumbing'
      fullPath: '/demo/plumbing'
      preLoaderRoute: typeof DemoPlumbingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/photography': {
      id: '/demo/photography'
      path: '/demo/photography'
      fullPath: '/demo/photography'
      preLoaderRoute: typeof DemoPhotographyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/lawyer': {
      id: '/demo/lawyer'
      path: '/demo/lawyer'
      fullPath: '/demo/lawyer'
      preLoaderRoute: typeof DemoLawyerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/landscaping': {
      id: '/demo/landscaping'
      path: '/demo/landscaping'
      fullPath: '/demo/landscaping'
      preLoaderRoute: typeof DemoLandscapingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/fitness': {
      id: '/demo/fitness'
      path: '/demo/fitness'
      fullPath: '/demo/fitness'
      preLoaderRoute: typeof DemoFitnessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/dental': {
      id: '/demo/dental'
      path: '/demo/dental'
      fullPath: '/demo/dental'
      preLoaderRoute: typeof DemoDentalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/autorepair': {
      id: '/demo/autorepair'
      path: '/demo/autorepair'
      fullPath: '/demo/autorepair'
      preLoaderRoute: typeof DemoAutorepairRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ServicesRouteChildren {
  ServicesSlugRoute: typeof ServicesSlugRoute
}

const ServicesRouteChildren: ServicesRouteChildren = {
  ServicesSlugRoute: ServicesSlugRoute,
}

const ServicesRouteWithChildren = ServicesRoute._addFileChildren(
  ServicesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  CardRoute: CardRoute,
  ContactRoute: ContactRoute,
  PortfolioRoute: PortfolioRoute,
  PricingRoute: PricingRoute,
  PrivacyRoute: PrivacyRoute,
  SecurityRoute: SecurityRoute,
  ServicesRoute: ServicesRouteWithChildren,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TermsRoute: TermsRoute,
  DemoAutorepairRoute: DemoAutorepairRoute,
  DemoDentalRoute: DemoDentalRoute,
  DemoFitnessRoute: DemoFitnessRoute,
  DemoLandscapingRoute: DemoLandscapingRoute,
  DemoLawyerRoute: DemoLawyerRoute,
  DemoPhotographyRoute: DemoPhotographyRoute,
  DemoPlumbingRoute: DemoPlumbingRoute,
  DemoRealestateRoute: DemoRealestateRoute,
  DemoRestaurantRoute: DemoRestaurantRoute,
  DemoSalonRoute: DemoSalonRoute,
  DemoIndexRoute: DemoIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
